model_name: distil-whisper-large-v3
quantization_type: float32
device_type: cpu
show_clipboard_window: true
curate_transcription: true
supported_quantizations:
  cpu:
  - float32
  cuda:
  - float16
  - bfloat16
  - float32
